name: working on pem file

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
   login_ec2 :
    name: 'login ec2'
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            
        run: |
          echo "$PRIVATE_KEY" > private.txt
          cat private.txt
          echo "$AWS_ACCESS_KEY_ID" > aws_access_key.txt
          cat aws_access_key.txt
          echo "Hello from Github Actions" > file1.txt
          cat file1.txt
          
          
