name: working on pem file

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
   login_ec2 :
    name: 'login ec2'
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2 
      - name: login to ec2 instance
            
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER_NAME }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOSTNAME }}
      - name: Listing files
        run: |
           echo " List all the files created:"
           ls -latr
          
      - name: login the server
        run: |
          ssh staging  '
          
            #Now we have got the access of EC2 and we will start the deploy .
            touch myfile.txt
            echo "This is second line added" >> myfile.txt            
          '
        
          
